### PR TITLE
Update Version - Angular 16

### PR DESCRIPTION
**Pull request by alidihaw**

### CODE REVIEW

**Comment by alvarotrigo** [comment]
Thanks @alidihaw ! 🙏 
Awesome work!

A couple of things:

- We need to include the latest fullPage.js version 4.0.20
image

- When updating, make sure to also remove the scrollOverflow.min.js file, that's not necessary anymore on the latest fullPage.js version
image

- You find the types for fullPage.js 4 here:
https://github.com/alvarotrigo/react-fullpage/blob/master/types/index.d.ts

I think once that's done, we are ready.

**Comment by alidihaw** [comment]
@alvarotrigo 
I just updated some section, here the list:

- update fullpage.js to 4.0.20
- replace all @angular-devkit/build-ng-packagr to ng-packagr
- fix dependency conflict
- update interface
- remove node_modules/fullpage.js/vendors/scrolloverflow.min.js

**Comment by ArjanKw** [comment]
Thank you for your work @alidihaw ! I tried out your pullrequest and got it working with Angular 16. Angular 17 gave me some trouble.

I never wrote an Angular library, but might have some suggestions. If you agree with them, I could make a PR on your PR, or you can change it yourself.

- According to the [Angular Docs](https://angular.io/guide/creating-libraries#publishing-libraries): "If you intend to publish your library to npm, compile with partial-Ivy code by setting "compilationMode": "partial" in tsconfig.prod.json. This partial format is stable between different versions of Angular, so is safe to publish to npm."
- The code now is directly tied to a specific version of Angular. Isn't it better to [change the dependencies to peer dependencies](https://stackoverflow.com/a/69671222) and allow newer versions? With the partial compilation mode the code should be compatible with Angular 12+, so the semantic versioning could change to ">12"
- The library is now dependent on "core-js". [According to this](https://stackoverflow.com/questions/56892243/is-not-core-js-needed-anymore), the CLI is now responsible for the polyfills, so core-js isn't necessary anymore. Also, the build now gives a message that the version of core-js is deprecated. So I would suggest to remove this.
- [According to node-sass](https://www.npmjs.com/package/node-sass) the version of node-sass depends on the version of Node. So changing it to a peer dependency with ">7" as semantic version, seems to enable people to install the correct version based on their environment.

**Comment by alvarotrigo** [comment]
Awesome! Thanks for your comments @ArjanKw! 👍 

@alidihaw do you agree with those comments?

**Comment by alidihaw** [comment]
@ArjanKw , Thanks for some suggestion 👍

@alvarotrigo , I have updated for, its already included to this pr:
  - Remove core-js & node sass from package
  - No need peer dependency for node sass (User can use: ^4.0.0 || ^5.0.0 || ^6.0.0 || ^7.0.0 || ^8.0.0)
  - Change to ES2022
  - Peer Dependency for Angular - >12
  - "compilationMode": "partial" - is safe to publish to npm.

**Comment by alvarotrigo** [comment]
@alidihaw thanks again! 👍 🙏

**Pull request merged**
